version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: Persimmon.VisualStudio.TestExplorer.Setup\bin\Release\Persimmon.VisualStudio.TestExplorer.Setup.msi
  name: Persimmon.VisualStudio.TestExplorer.Setup.msi
